implementation

diff --git a/.github/workflows/_deploy-application.scalingo.reusable.yml b/.github/workflows/_deploy-application.scalingo.reusable.yml
--- a/.github/workflows/_deploy-application.scalingo.reusable.yml
+++ b/.github/workflows/_deploy-application.scalingo.reusable.yml
@@ -31,8 +31,16 @@ jobs:
         run: scalingo login --api-token=${{ secrets.SCALINGO_API_TOKEN }}
 
 #TODO Better readability for condition ?
-      - name: Create the application with its specific environment if it does not exist
-        run: if (( $(scalingo apps | grep -c ${{ inputs.application-full-name }}) == 0 )); then scalingo create ${{ inputs.application-full-name }}; else echo 'app exists already'; fi
+      - name: Create the application with its specific environment if it does not exist (trimmed to the scalingo limit of 47 characters)
+        run: |
+          echo ${{ inputs.application-full-name }}
+          set +e
+          APP_ALREADY_EXIST=$(scalingo apps | grep -c ${{ inputs.application-full-name }})
+          set -e
+          if [[ $APP_ALREADY_EXIST -eq 0 ]]; then scalingo create ${{ inputs.application-full-name }}; else echo 'Error app exists already or has an invalid name'; fi
+
+#      - name: Create the application with its specific environment if it does not exist
+#        run: if (( $(scalingo apps | grep -c ${{ inputs.application-full-name }}) == 0 )); then scalingo create ${{ inputs.application-full-name }}; else echo 'Error app exists already or has an invalid name'; fi
 
       - name: Generate transient ssh-keys then add the public key to the logged account for deployment
         run: |
@@ -55,6 +63,7 @@ jobs:
     steps:
       - name: Retrieve project files for current branch
         uses: actions/checkout@v3
+
       - name: Initialise a local git repository for deployment (a scalingo deployment is a push to their remote)
         run: |
           rm -rf .git
